### ISSUE TITLE
Script fails to execute

### ISSUE THREAD

**Issue by cassandrauser** [moovel/openvpn#1]
I used it in OpsWorks and deployed the instance. 
But when I tried to run the ./infrastructure.sh start command as mentioned in the instruction it through some weird errors message : 

root@openvpn2:/var/lib/aws/opsworks/cache.stage2/cookbooks/deploy# ./infrastructure.sh start
bash: ./infrastructure.sh: Permission denied

root@openvpn2:/var/lib/aws/opsworks/cache.stage2/cookbooks/deploy# chmod 755 infrastructure.sh

root@openvpn2:/var/lib/aws/opsworks/cache.stage2/cookbooks/deploy# ./infrastructure.sh start
Searching for ID of VPC 'moovel-dev'...
./infrastructure.sh: line 105: jq: command not found
./infrastructure.sh: line 105: aws: command not found

**Comment by jorgebsa** [comment]
you need to install the [amazon cli](https://aws.amazon.com/cli/?nc1=h_ls) and [jq](https://stedolan.github.io/jq/download/) in order to be able to execute inrastructure.sh
